module.exports = [
  'There\'s no answer... when there\'s no question...',
  'Courage is rightly esteemed the first of human qualities... because it is the quality which guarantees all others.',
  'Your destiny is set by the choices you make.',
  'Management is doing things right; leadership is doing the right things.',
  'You are free to choose a life to live, or one that\'s left to lose...',
  'Living really is the only way to know.',
  'You see things; and you say, "Why"? But I dream things that never were; and I say, "What the heck. Why not?"',
  'Because limits, like fears, are often just illusions.',
  'All the forces in the world are not so powerful as an idea whose time has come.',
  'Life is not our fantasy predictions of the future or our glory days of the past. Life is that thing that is happening to you as you read this.',
  'Everything is new once.',
  'We all fall in love, and we all fail into life, we look for the truth, on the edge of a knife!',
  'Everything you want is on the other side of fear.',
  'The mystery of life isn\'t a problem to solve, but a reality to experience.',
  'The absence of evidence is not the evidence of absence.',
  'Fear does not prevent death. It prevents life.',
  'Simple things should be simple, and complex things should be possible.',
  'Someday is a disease that will take your dreams to the grave with you.',
  'It is said there are two ways to be unhappy: one is not getting what you want, the other is getting what you want!',
  'You\'ve got to be cruel to be kind.- Hamlet',
  'All the world\'s a stage.',
  'Such stuff as dreams are made.',
  'Brevity is the soul of wit.',
  'Infinite Variety.',
  'You can\'t have too much of a good thing.',
  'Forever and a day.',
  'Now that we can do anything, what should we do?',
  'If you spend too much time thinking about a thing, you\'ll never get it done.',
  'He who can no longer pause to wonder and stand rapt in awe, is as good as dead; his eyes are closed.',
  'When you don\'t create things, you become defined by your tastes rather than ability. Your tastes only narrow & exclude people. So create.',
  'Trust is earned through actions, not just words.',
  'I am always doing that which I can not do, in order that I may learn how to do it.',
  'Always be yourself, express yourself, have faith in yourself, do not go out and look for a successful personality and duplicate it.',
  'I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.',
  'A wise man can learn more from a foolish question than a fool can learn from a wise answer.',
  'If you love life, don\'t waste time, for time is what life is made up of.',
  'A goal is not always meant to be reached, it often serves simply as something to aim at.',
  'Mistakes are always forgivable, if one has the courage to admit them.',
  'I\'m not in this world to live up to your expectations and you\'re not in this world to live up to mine.',
  'The Human Brain is a wonderful thing. It starts working the moment you are born, and never stops until you stand up to speak in public.',
  'Risking nothing is a big risk.',
  'I must be cruel, only to be kind: Thus bad begins and worse remains behind.',
  'The most thought-provoking thing in our thought-provoking time is that we are still not thinking.',
  'Only put off until tomorrow what you are willing to die having left undone.',
  'I\'m a success today because I had a friend who believed in me and I didn\'t have the heart to let him down.',
  'If something is important enough, even if the odds are against you, you should still do it.',
  'If you are depressed, you are living in the past. If you are anxious, you are living in the future.',
  'A revolução contemporânea é a incerteza, a do 18 foi a francesa, a do 20, é a incerteza.',
  'Anyone who loves an ordinary, everyday person and is loved by her is happy – despite of the dark side of life.',
  'Fighting styles are nothing more than the application of them.',
  'The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.',
  'Does the walker choose the path, or the path the walker?',
  'The days are long, but the years fly by.',
  'Don\'t sell out what you want most for what you want now.',
  'What would you do if you weren\'t afraid?',
  'If you don\'t make mistakes, you\'re not working on hard enough problems. And that\'s a big mistake.',
  'Either write something worth reading or do something worth writing.',
  'Often when you think you\'re at the end of something, you\'re at the beginning of something else.',
  'My face is reflected in the water. It\'s a shining grin full of hope… Or it could be a look of somber silence struggling with fear...',
  'Sometimes magic is just someone spending more time on something than anyone else might reasonably expect.',
  'To be somebody or to do something.',
  'Even the tallest mountains have animals that, when they stand on it, are higher than the mountain.',
  'Don\'t ever take a fence down until you know why it was put up.',
  'Take everything that\'s bright and beautiful in you and introduce it to the shadow side of yourself.',
  'You have to finish things — that\'s what you learn from, you learn by finishing things.',
  'It\'s so hard to forget pain, but it\'s even harder to remember sweetness. We have no scar to show for happiness. We learn so little from peace.',
  'At crack of dawn hazy remains above my mind...',
  'Reality is merely an illusion, albeit a very persistent one.',
  'People are disturbed not by things but by their view of things.',
  'We suffer more often in imagination than in reality.',
  'Most of what we see that we call information doesn\'t inform, and most questions do not have a quest.',
  'To dare is to lose one\'s footing momentarily. Not to dare is to lose oneself.',
  'Ever tried, ever failed, no matter. Try again, fail again, fail better.',
  'Life is either a daring adventure or nothing at all.',
  'The best way to complain is to make things.',
  'Nothing is more terrible than activity without insight.',
  'Stop imagining what\'s going to work. Find out for real.',
  'The trouble with so many of us is that we underestimate the power of simplicity.',
  'In theory, there is no difference between theory and practice. But, in practice, there is.',
  'Who you are, what you think, feel, and do, what you love — is the sum of what you focus on.',
  'Emptiness is the fasting of the mind.',
  'You are ever going to be happy with what you get if you can\'t be happy with you have.',
  'It\'s not what you look at that matters, it\'s what you see.',
  'Strategy without tactics is the slowest route to victory. Tactics without strategy is the noise before defeat.',
  'Clarity about what matters provides clarity about what does not.',
  'There will come a time when you believe everything is finished. That will be the beginning.',
  'Life is like a ten speed bicycle. Most of us have gears we never use.',
  'No one ever discovered anything new by coloring inside the lines.',
  'When do the waving lights and shadows of dawning consciousness cast their print upon the mind of a child?',
  'The problem is not the problem. It\'s your attitude to the problem, that\'s the problem'
]
